Repository Full-Tortuga/decide-full-tortuga-autenticacion, pull requests merged in 2022-01, with the labels that each got.

#49 Cambio en la redirección del botón cerrar sesión
  decide/authentication/templates/welcome.html
Labels: bug, high-priority

#52 Only auth coverage
  .github/workflows/heroku.yml
Labels: test, integration

#53 INTEGRADO LOGIN DE LDAP Y FORM DE REACT
  decide/authentication/static/css/main.fc5a4140.css
  decide/authentication/static/js/main.3ccb80af.js
  decide/authentication/static/main.f3eff200.js
  decide/authentication/templates/authentication_frontend/src/SignInUp/LoginLDAP.tsx
  decide/authentication/templates/authentication_frontend/src/SignInUp/SignInUp.tsx
  decide/authentication/templates/form.html
  decide/authentication/templates/login_ldap_view.html
  decide/authentication/templates/welcome.html
  decide/authentication/urls.py
Labels: feature, gui

#50 Test/forms
  .github/workflows/heroku.yml
  decide/authentication/tests.py
  requirements.txt
Labels: low-priority, test

#57 Improved user interface login
  decide/authentication/static/img/login.png
  decide/authentication/static/img/signup.png
  decide/authentication/static/main.10613914.css
  decide/authentication/static/main.159e7c5b.css
  decide/authentication/static/main.ba75df00.js
  decide/authentication/templates/authentication_frontend/package.json
  decide/authentication/templates/authentication_frontend/src/SignInUp/Login.tsx
  decide/authentication/templates/authentication_frontend/src/SignInUp/LoginLDAP.tsx
  decide/authentication/templates/authentication_frontend/src/SignInUp/Register.tsx
  decide/authentication/templates/authentication_frontend/src/SignInUp/SignInUp.tsx
  decide/authentication/templates/authentication_frontend/src/SignInUp/Utils.ts
  decide/authentication/templates/authentication_frontend/src/SignInUp/index.css
  decide/authentication/templates/authentication_frontend/src/index.tsx
  decide/authentication/templates/form.html
Labels: gui, low-priority

#51 Tests selenium
  decide/authentication/templates/welcome.html
  decide/authentication/tests.py
Labels: med-priority, test

#61 <bug>: <ldap> Votaciones arregladas para usuarios LDAP
  decide/authentication/urls.py
  decide/authentication/views.py
Labels: bug, high-priority

#59 <fix>: <ldap> USUARIO DE PRUEBA EN LA IMAGEN DE DOCKER PARA PRUEBAS
  .github/workflows/heroku.yml
  README.md
  decide/authentication/tests.py
Labels: bug, test
